dist: focal
language: python
python:
  - '3.7'
  - '3.8'
services:
  - postgresql
addons:
  postgresql: '12'
  apt:
    packages:
      - postgresql-12
      - postgresql-client-12
install:
  - PYTHON=python make
before_script:
  - createdb newdle_tests
  - source .venv/bin/activate
script:
  - make lint
  - make test
notifications:
  email: false
